version: 0.2

phases:
  pre_build:
    commands:
      - make login-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION=${COMMIT_HASH:=latest}
  build:
    commands:
      - make VERSION=$VERSION build
  post_build:
    commands:
      - make VERSION=$VERSION publish
      - make VERSION=$VERSION write-image-definitions
artifacts:
    files: imagedefinitions.json